// SPDX-License-Identifier: MIT
//! Raw FFI bindings to libra, generated by `build.rs` via bindgen.
//!
//! When the libra header is missing at build time, `build.rs` writes a stub
//! `bindings.rs` containing only comments. That keeps `cargo check` green so
//! contributors can iterate on the Rust side before submodules are populated.
//! The actual link will fail later, which is expected during the M1 scaffold.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
